Revert "fix compilation error: "Never use <bits/nan.h> directly; include <math.h> instead." (glibc)"
This reverts commit 54da7ce7dafcc2fe6212ce3fab677956c9d5188c.